title: My blog 1

theme: minima

# Minima: custom header links
minima:
  nav_pages:
    - _pages/contents.md
    - _pages/frontpage.md
  social_links:
    - title: title
    - icon: bluesky
    - url: https://bsky.app/

include:
  - _pages
    
exclude: 
    - Gemfile
    - Gemfile.lock
    - README.md
    - index.md
